version: "2.1"
services:
  places-ms:
    build: .
    ports:
      - "5000:5000"
    links:
      - places-db:sql_srv
    depends_on:
      places-db:
        condition: service_healthy
  places-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: places-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3308:3306"

